### ISSUE TITLE
Android builds fail for Qt5.7 and Qt5.8

### ISSUE THREAD

**Issue by fmeerkoetter** [KDAB/GammaRay#367]
I've checked out the 2.7 branch (e889726).

Configured the project like this:

`cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-android.cmake -DGAMMARAY_PROBE_ONLY_BUILD=true -DCMAKE_PREFIX_PATH=/usr/local/Qt/5.8/android_armv7/ -DCMAKE_INSTALL_PREFIX=/usr/local/Qt/5.8/android_armv7/ ..`

and ran make

```
cd /home/fmee/projects/foss/GammaRay/android-build-5.8/probe && /usr/local/Android/android-ndk-r14b//toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++  --sysroot=/usr/local/Android/android-ndk-r14b//platforms/android-14/arch-arm  -DANDROID -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -I/home/fmee/projects/foss/GammaRay/android-build-5.8/probe -I/home/fmee/projects/foss/GammaRay/probe -isystem /usr/local/Android/android-ndk-r14b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /usr/local/Android/android-ndk-r14b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /usr/local/Qt/5.8/android_armv7/include/QtGui/5.8.0 -isystem /usr/local/Qt/5.8/android_armv7/include/QtGui/5.8.0/QtGui -isystem /usr/local/Qt/5.8/android_armv7/include/QtCore/5.8.0 -isystem /usr/local/Qt/5.8/android_armv7/include/QtCore/5.8.0/QtCore -I/home/fmee/projects/foss/GammaRay -I/home/fmee/projects/foss/GammaRay/3rdparty -I/home/fmee/projects/foss/GammaRay/android-build-5.8 -I/usr/local/Qt/5.8/android_armv7/include -I/usr/local/Qt/5.8/android_armv7/include/QtGui -I/usr/local/Qt/5.8/android_armv7/include/QtCore -I/usr/local/Qt/5.8/android_armv7/./mkspecs/android-g++ -I/usr/local/Qt/5.8/android_armv7/include/QtWidgets -I/usr/local/Qt/5.8/android_armv7/include/QtPrintSupport -I/usr/local/Qt/5.8/android_armv7/include/QtSvg -I/usr/local/Qt/5.8/android_armv7/include/QtNetwork -I/usr/local/Qt/5.8/android_armv7/include/QtTest -I/usr/local/Qt/5.8/android_armv7/include/QtConcurrent -I/home/fmee/projects/foss/GammaRay/android-build-5.8/core -I/home/fmee/projects/foss/GammaRay/android-build-5.8/common  -fvisibility=hidden -fvisibility-inlines-hidden -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wreorder -Wall -Wextra -pedantic -Woverloaded-virtual -Winit-self -Wmissing-include-dirs -Wunused -Wundef -Wpointer-arith -Wmissing-noreturn -Werror=return-type -Wswitch -std=gnu++0x -fno-operator-names -Wzero-as-null-pointer-constant -O3 -DNDEBUG -fPIC   -o CMakeFiles/gammaray_probe_obj.dir/hooks.cpp.o -c /home/fmee/projects/foss/GammaRay/probe/hooks.cpp
/home/fmee/projects/foss/GammaRay/plugins/widgetinspector/widgetinspector_export_actions.cpp: In function 'void gammaray_save_widget_to_pdf(QWidget*, const QString&)':
/home/fmee/projects/foss/GammaRay/plugins/widgetinspector/widgetinspector_export_actions.cpp:79:5: error: 'QPrinter' was not declared in this scope
     QPrinter printer(QPrinter::ScreenResolution);
     ^
/home/fmee/projects/foss/GammaRay/plugins/widgetinspector/widgetinspector_export_actions.cpp:80:5: error: 'printer' was not declared in this scope
     printer.setOutputFileName(fileName);
     ^
/home/fmee/projects/foss/GammaRay/plugins/widgetinspector/widgetinspector_export_actions.cpp:81:29: error: 'QPrinter' is not a class, namespace, or enumeration
     printer.setOutputFormat(QPrinter::PdfFormat);
                             ^
/home/fmee/projects/foss/GammaRay/plugins/widgetinspector/widgetinspector_export_actions.cpp:82:40: error: 'QPrinter' is not a class, namespace, or enumeration
     printer.setPageMargins(0, 0, 0, 0, QPrinter::DevicePixel);
                                        ^
/home/fmee/projects/foss/GammaRay/plugins/widgetinspector/widgetinspector_export_actions.cpp:83:42: error: 'QPrinter' is not a class, namespace, or enumeration
     printer.setPaperSize(widget->size(), QPrinter::DevicePixel);
                                          ^
make[2]: Verzeichnis „/home/fmee/projects/foss/GammaRay/android-build-5.8“ wird verlassen
[ 13%] Built target gammaray_styleinspector_plugin_automoc
```

Commenting out HAVE_QT_PRINTSUPPORT in config-gammaray.h fixes the issue for me.

I am building on a (K)ubuntu16.04.

For Qt5.6 the builds works out of the box. 5.7 and 5.8 both have this issue.

**Comment by vkrause** [comment]
Works with 5.9, but I can indeed reproduce this with the official 5.8 packages.

**Comment by vkrause** [comment]
It's due to Qt being built with QT_NO_PRINTER, a configuration flag we don't handle yet.

**Comment by vkrause** [comment]
Fixed in the 2.8 branch, merge to master follows shortly.
