### ISSUE TITLE
Compile error C2664 on Windows

### ISSUE THREAD

**Issue by bterrier** [KDAB/GammaRay#561]
I have bee trying to compile GammaRay 2.10 on Windows with both MSVC2017 32 bits and MinGW 64 bits with the official Qt 5.12.4 builds.

In both cases it fails at the same line.

With MSVC:
```
GammaRay\plugins\qmlsupport\qmlattachedpropertyadaptor.cpp(59): error C2664: 'void
QVector<int>::push_back(T &&)': cannot convert argument 1 from 'const Key' to 'const T &'
        with
        [
            T=int
        ]
        and
        [
            Key=QQmlAttachedPropertiesFunc
        ]
        and
        [
            T=int
        ]
```

With MinGW:

```
GammaRay\plugins\qmlsupport\qmlattachedpropertyadaptor.cpp:59:43: error: no matching
function for call to 'push_back(QObject* (* const&)(QObject*))'
         m_attachedTypes.push_back(it.key());
                                           ^
In file included from C:/Qt/5.12.4/mingw73_64/include/QtCore/QVector:1:0,
                 from GammaRay/core/propertyadaptor.h:36,
                 from GammaRay\plugins\qmlsupport\qmlattachedpropertyadaptor.h:32,
                 from GammaRay\plugins\qmlsupport\qmlattachedpropertyadaptor.cpp:29:
```

**Comment by winterz** [comment]
it's very possible that 2.10 won't build with Qt5.12.4
We released version 2.11 about 2 weeks ago.  try it.
https://github.com/KDAB/GammaRay/releases/tag/v2.11.0

**Comment by bterrier** [comment]
2.11 is working
