### ISSUE TITLE
FTBFS with Qt 5.5

### ISSUE THREAD

**Issue by danvratil** [KDAB/GammaRay#136]
/builddir/build/BUILD/gammaray-2.2.1/plugins/widgetinspector/paintbuffermodel.h:32:62: fatal error: private/qpaintbuffer_p.h: No such file or directory

qpaintbuffer_p.h has been removed in Qt 5.5 (qtbase commit bcf6a3eb34670950302ab8cfaede024c4af38e75)

**Comment by krf** [comment]
See https://github.com/KDAB/GammaRay/pull/137 -- does that fix the issue for you?

**Comment by vkrause** [comment]
The backport is fine with me of course, just wondering if we shouldn't do a proper 2.3 release with full 5.5 support soonish, now that 5.5 is about to be released?

**Comment by krf** [comment]
Makes sense to me.

There should be a *released* version out there which compiles fine with Qt 5.5. Either 2.3 or 2.2.2 would be fine with me (2.2.2 would be quicker to release, I presume, only contains bug fixes)

**Comment by danvratil** [comment]
I can confirm that with the patch GammaRay succesfully compiles with Qt 5.5. Thanks for the quick response :)

**Comment by vkrause** [comment]
Got integrated into 2.2 branch.
