### ISSUE TITLE
2.9.1 fails to build against Qt 5.12 alpha

### ISSUE THREAD

**Issue by Vogtinator** [KDAB/GammaRay#508]
The changelog states that 2.9.1 builds fine against 5.12, but it fails:
```
[  335s] /home/abuild/rpmbuild/BUILD/gammaray-2.9.1/plugins/qmlsupport/qmlbindingprovider.cpp: In member function 'void GammaRay::QmlBindingProvider::fetchSourceLocationFor(GammaRay::BindingNode*, QQmlBinding*) const':
[  335s] /home/abuild/rpmbuild/BUILD/gammaray-2.9.1/plugins/qmlsupport/qmlbindingprovider.cpp:72:28: error: variable 'QQmlSourceLocation loc' has initializer but incomplete type
[  335s]          QQmlSourceLocation loc = function->sourceLocation();
[  335s]                             ^~~
[  335s] /home/abuild/rpmbuild/BUILD/gammaray-2.9.1/plugins/qmlsupport/qmlbindingprovider.cpp:72:59: error: invalid use of incomplete type 'struct QQmlSourceLocation'
[  335s]          QQmlSourceLocation loc = function->sourceLocation();```

**Comment by krf** [comment]
@Vogtinator We fixed /one/ compilation issue with Qt 5.12, but in the meantime your issue popped up I think.

Your issue was fixed with 2cd4585e (but it's not part of 2.9.1). Will be part of 2.9.2 when it comes.

**Comment by Vogtinator** [comment]
Thanks, I'll backport https://github.com/KDAB/GammaRay/commit/2cd4585e287a2bcf80572505537e5e75d020c5f5 and reopen if it still fails.

**Comment by Vogtinator** [comment]
Failed again, seems like https://github.com/KDAB/GammaRay/commit/d0c9f9c8a0c62c53812c25e5bd77119f214cd1f8 is necessary as well.

**Comment by krf** [comment]
Likely, they're all in the 2.9 branch, though:

```
* 2cd4585e - (origin/5.11) Compile with Qt 5.12 (6 weeks ago) <Volker Krause>
* d0c9f9c8 - Adapt to Qt 5.12 V4 identifier changes (7 weeks ago) <Volker Krause>
* d31144f9 - (tag: v2.9.1) various - prep for 2.9.1 release (9 weeks ago) <Allen Winter>
```
