### ISSUE TITLE
GammaRay build problem on openSUSE Leap 42.2 (undefined references in libbfd.a)

### ISSUE THREAD

**Issue by krf** [KDAB/GammaRay#386]
Reported by mail from an OpenSuse user:

I build with Qt 5.9 from qt.io, so I add its 'bin' folder to PATH.

Target 'core/CMakeFiles/gammaray_core.dir/all' gives this output:
```
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libbfd.a(elflink.o): In function `elf_link_add_object_symbols': 
/home/abuild/rpmbuild/BUILD/binutils-2.26.1/build-dir/bfd/../../bfd/elflink.c:4733: undefined reference to `objalloc_free_block' 
/home/abuild/rpmbuild/BUILD/binutils-2.26.1/build-dir/bfd/../../bfd/elflink.c:5027: undefined reference to `_sch_istable' 
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libbfd.a(elflink.o): In function `bfd_elf_size_dynamic_sections': 
/home/abuild/rpmbuild/BUILD/binutils-2.26.1/build-dir/bfd/../../bfd/elflink.c:6213: undefined reference to `lbasename' 
/home/abuild/rpmbuild/BUILD/binutils-2.26.1/build-dir/bfd/../../bfd/elflink.c:6444: undefined reference to `lbasename' 
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libbfd.a(pei-x86_64.o): In function `pex64_bfd_print_pdata_section':
. . .
collect2: error: ld returned 1 exit status
```

To build, I manually add -liberty and -lz to ./build/core/CMakeFiles/gammaray_core.dir/link.txt. The build is then successful.

I think some cmake files consider these libraries as dependencies and do not specify them explicitly.

https://github.com/symengine/symengine/issues/630
