### ISSUE TITLE
current gammaray does not compile with Qt5.14

### ISSUE THREAD

**Issue by jriddell** [KDAB/GammaRay#596]
The current release of Gammaray no longer compiles with Qt 5.14, could we have a new release?  
quickinspector/quickinspector.cpp:658:40: error: no members matching ‘QSGAbstractSoftwareRenderer::renderableNodes’ in ‘class QSGAbstractSoftwareRenderer’
https://build.neon.kde.org/job/bionic_stable_extras_gammaray_bin_amd64/16/console

**Comment by winterz** [comment]
should be fixed in the 2.11.1 release
