### ISSUE TITLE
Compilation Error with QT 5.14.1 and Latest Dev Snapshots

### ISSUE THREAD

**Issue by Chicou** [KDAB/GammaRay#591]
Hi all, i have just updated to QT 5.14.1 and when compiling with "Latest Development Snapshot" i have this compilation error  ( for msvc2017_64 ) : 
It compile well with QT 5.13.2 and "Latest Stable"
my cmd line is : 

cmake -DQt5Code_DIR=V:/Qt/5.14.0/msvc2017_64/lib/cmake/Qt5Core -DQt5_DIR=V:/Qt/5.14.0/msvc2017_64/lib/cmake/Qt5 -DCMAKE_BUILD_TYPE=Rel -DCMAKE_INSTALL_PREFIX=V:/Qt/Tools/GammaRay -DCMAKE_PREFIX_PATH=V:/Qt/5.14.0/msvc2017_64 -G "NMake Makefiles" ..
nmake
nmake install

The compilation error on nmake : 

[ 59%] Built target gammaray_quickinspector_autogen
[ 59%] Building CXX object plugins/quickinspector/CMakeFiles/gammaray_quickinspector.dir/quickinspector.cpp.obj
quickinspector.cpp
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(666): error C2039: 'renderableNodes': is not a member of 'QSGAbstractSoftwareRenderer'
v:\qt\5.14.1\msvc2017_64\include\qtquick\5.14.1\qtquick\private\qsgabstractsoftwarerenderer_p.h(65): note: see declaration of 'QSGAbstractSoftwareRenderer'
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(666): error C2873: 'renderableNodes': symbol cannot be used in a using-declaration
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(698): error C2039: 'renderableNodes': is not a member of 'SGSoftwareRendererPrivacyViolater'
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(662): note: see declaration of 'SGSoftwareRendererPrivacyViolater'
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(700): error C3536: 'iterator': cannot be used before it is initialized
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(700): error C2100: illegal indirection
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(704): error C2039: 'renderableNodes': is not a member of 'SGSoftwareRendererPrivacyViolater'
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(662): note: see declaration of 'SGSoftwareRendererPrivacyViolater'
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(705): error C2100: illegal indirection
V:\Qt\Tools\KDAB-GammaRay-v2.11.0-109-0adaa43\plugins\quickinspector\quickinspector.cpp(1002): warning C4996: 'QSGNode::dirtyState': was declared deprecated
V:\Qt\5.14.1\msvc2017_64\include\QtQuick/qsgnode.h(149): note: see declaration of 'QSGNode::dirtyState'
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe' : return code '0x2'

**Comment by Chicou** [comment]
Hi all,
Finally i achieve to compile it 👍 
The code as been fixed in the gitub  "GammaRay-master" ( akreuzkamp Revert "Disable QSGASR::renderableNodes for 5.14.0 only" ), do not take the zip from the web site "Latest Development Snapshot" prefer the latest
