### ISSUE TITLE
MSVC2019 (x64) build with Qt 6.1.3 fails to compile

### ISSUE THREAD

**Issue by CraigPersonal100** [KDAB/GammaRay#726]
I am trying to build Gammaray with MSVC 2019 (x64) and Qt 6.1.3 so that I can debug my PySide6 application.

I am using the `x64 Native Tools Command Prompt for VS 2019` and I invoked the compiler with:

`cmake -DCMAKE_PREFIX_PATH=D:\Qt\6.1.3\msvc2019_64 -G "NMake Makefiles" .. `

This gave the error:

```
[ 12%] Building CXX object core/CMakeFiles/gammaray_core.dir/tools/metatypebrowser/metatypesmodel.cpp.obj metatypesmodel.cpp
D:\Qt\GammaRay\core\tools\metatypebrowser\metatypesmodel.cpp(82): error C2039: 'IsConst': is not a member of 'QMetaType'D:\Qt\6.1.3\msvc2019_64\include\QtCore/qmetatype.h(292): note: see declaration of 'QMetaType'
D:\Qt\GammaRay\core\tools\metatypebrowser\metatypesmodel.cpp(82): error C2065: 'IsConst': undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0x2'
Stop.                                                                                                                                                                  
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop. 
```

The key bit seems to be `D:\Qt\GammaRay\core\tools\metatypebrowser\metatypesmodel.cpp(82): error C2039: 'IsConst': is not a member of 'QMetaType'D:\Qt\6.1.3\msvc2019_64\include\QtCore/qmetatype.h(292)`.

Am I using an incorrect branch of gammaray (master)? Is there anything I can do to get around this while I wait for a fix?

**Comment by dantti** [comment]
I think GammaRay can only be build with Qt 6.2 due some Qt issues that were fixed there, we might need to increase the minimum version.

**Comment by Waqar144** [comment]
Yeah, but it should be able to compile.

Please try latest master, the issue above should be gone.

**Comment by dantti** [comment]
There were some issue in the metatype that might render it useless tho, which is why I'm not sure letting < 6.2 is a good idea.
